
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantWS {


    /**
     * 
     * @return
     *     returns java.util.List<service.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "http://service/", className = "service.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "http://service/", className = "service.GetEtudiantsResponse")
    @Action(input = "http://service/EtudiantWS/getEtudiantsRequest", output = "http://service/EtudiantWS/getEtudiantsResponse")
    public List<Etudiant> getEtudiants();

    /**
     * 
     * @param id
     * @return
     *     returns service.Etudiant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiant", targetNamespace = "http://service/", className = "service.GetEtudiant")
    @ResponseWrapper(localName = "getEtudiantResponse", targetNamespace = "http://service/", className = "service.GetEtudiantResponse")
    @Action(input = "http://service/EtudiantWS/getEtudiantRequest", output = "http://service/EtudiantWS/getEtudiantResponse")
    public Etudiant getEtudiant(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param prenom
     * @param nom
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterEtudiant", targetNamespace = "http://service/", className = "service.AjouterEtudiant")
    @ResponseWrapper(localName = "ajouterEtudiantResponse", targetNamespace = "http://service/", className = "service.AjouterEtudiantResponse")
    @Action(input = "http://service/EtudiantWS/ajouterEtudiantRequest", output = "http://service/EtudiantWS/ajouterEtudiantResponse")
    public Boolean ajouterEtudiant(
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

    /**
     * 
     * @param id
     * @param prenom
     * @param nom
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierEtudiant", targetNamespace = "http://service/", className = "service.ModifierEtudiant")
    @ResponseWrapper(localName = "modifierEtudiantResponse", targetNamespace = "http://service/", className = "service.ModifierEtudiantResponse")
    @Action(input = "http://service/EtudiantWS/modifierEtudiantRequest", output = "http://service/EtudiantWS/modifierEtudiantResponse")
    public Boolean modifierEtudiant(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerEtudiant", targetNamespace = "http://service/", className = "service.SupprimerEtudiant")
    @ResponseWrapper(localName = "supprimerEtudiantResponse", targetNamespace = "http://service/", className = "service.SupprimerEtudiantResponse")
    @Action(input = "http://service/EtudiantWS/supprimerEtudiantRequest", output = "http://service/EtudiantWS/supprimerEtudiantResponse")
    public Boolean supprimerEtudiant(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
